### ISSUE TITLE
数据集文件Readme

### ISSUE THREAD

**Issue by Changxiao11111** [weiyinwei/CLCRec#3]
作者您好，movielens数据集中Readme中没有写入东西，能否简单列举一下数据文件的表头，如user_item_dict.npy和user_item_train_dict.npy，非常感谢您。

**Comment by weiyinwei** [comment]
您好，感谢关注，我会尽快整理文件，然后重新release并加入一些说明。

**Comment by Changxiao11111** [comment]
好的，非常感谢
