### ISSUE TITLE
paper中公式的推导

### ISSUE THREAD

**Issue by wujcan** [weiyinwei/CLCRec#4]
请问能提供更加具体的公式（3）-（4）之间的公式的推导过程吗？非常感谢

**Comment by weiyinwei** [comment]
您好，我不明白您说的3-4公式间的推导是具体那一部分，3和4公式间已经给出了推导（虽然没有标注公式号）。

**Comment by wujcan** [comment]
> 您好，我不明白您说的3-4公式间的推导是具体那一部分，3和4公式间已经给出了推导（虽然没有标注公式号）。

比如说公式（3）是怎么从贝叶斯公式得到的，感觉中间有其他的独立性假设（除了X和Z的独立性）使得式子得以化简。可否给出具体每个式子的推导中间步骤。谢谢

**Comment by weiyinwei** [comment]
是的，还有假设user之间，item之间，user与没有交互的item之间是相互独立的。如果方便的话，您给我留一下邮箱吧，我可以给您邮件解答，我不大知道怎么在这里写公式。

**Comment by zzhuncle** [comment]
我也想知道公式是怎么推导的，请问可以发到我的邮箱里么，3294175303@qq.com
